
language: java
jdk: oraclejdk11

services:
  - docker

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.gradle/wrapper"

before_install:
  - chmod +x gradlew

stages:
  - build
  - test
  - pushImage
  - deploy

jobs:
  include:
    - stage: build
      language: java
      script: ./gradlew clean assemble
    - stage: test
      language: java
      script: ./gradlew check
    - stage: pushImage
      if: (branch = develop) AND (type = push)
      script: ./gradlew pushImage
    - stage: deploy
      if: (branch = develop) AND (type = push)
      script: bash scripts/deploy.sh -v $(./gradlew -q printVersion)