tg:
  token:
  username:

logging:
  level:
    root: INFO

server:
  port: 8083

sublearn:
  back:
    url: http://sub-learn-back:8080/api
    login:
    password:
  competition:
    url: http://sub-learn-competitions:8080/api/competition

spring:
  redis:
    host: redis
    port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
