version: '3.4'

services:
  sub-learn-telegram:
    image: almazic91/sub-learn-telegram
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
        SPRING_PROFILES_ACTIVE: default
        SERVER_PORT: 8080
        TG_TOKEN:
        TG_USERNAME:

  redis:
      container_name: redis
      image: redis
      restart: always
      ports:
        - "6379:6379"
        -
  rabbitmq:
      container_name: rabbitmq
      image: rabbitmq
      restart: always
      ports:
        - "5672:5672"