version: '3.4'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
