name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Assembling
      run: ./gradlew assemble --console=plain

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assembling
        run: ./gradlew assemble --console=plain
      - name: Testing
        run: ./gradlew check --stacktrace --console=plain

  publish:
    if: github.event_name == 'push' && (contains(github.ref, 'develop') || contains(github.ref, 'master'))
    runs-on: ubuntu-latest
    needs: [build, test]
    name: Push docker image
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Push docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./gradlew pushImage

  deploy:
    if: github.event_name == 'push' && (contains(github.ref, 'develop') || contains(github.ref, 'master'))
    runs-on: ubuntu-latest
    needs: [publish]
    name: Deploy on server
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: SH script for deploy develop
        if: github.event_name == 'push' && contains(github.ref, 'develop')
        env:
          PROJECT_TAG: TELEGRAM_IMAGE_VERSION
          DEPLOY_IP: 159.69.81.0
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: ./scripts/deploy.sh -v $(./gradlew -q printVersion)
        shell: bash

      - name: SH script for deploy master
        if: github.event_name == 'push' && contains(github.ref, 'master')
        env:
          PROJECT_TAG: TELEGRAM_IMAGE_VERSION
          DEPLOY_IP: ${{ secrets.DEPLOY_IP_MASTER }}
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: ./scripts/deploy.sh -v $(./gradlew -q printVersion)
        shell: bash